"""Generate a hash-pinned constraints file for the runtime closure.

Roadmap §1.3 asks for lock/constraints with hashes. A plain ``name==version``
list pins *what* to install; it does not pin *the bytes*. ``pip install
--require-hashes`` closes that gap: every distribution file must match a
recorded SHA-256, so a compromised or substituted artifact on the index is
rejected at install time.

The hashes are the SHA-256 digests PyPI publishes for each release file — the
same values ``pip`` verifies. They are fetched from the PyPI JSON API
(``/pypi/<name>/<version>/json``), not by downloading and hashing wheels
ourselves, so the generator is network-light and cannot disagree with what the
index actually serves. A version must list **every** distribution file's hash
(wheels and sdist), because pip accepts any one of them.

The network fetch (:func:`fetch_release_hashes`) is deliberately separated from
the rendering (:func:`render_constraints`), so the formatting — the part with
the fiddly ``pip`` line continuations — is unit-tested without a network.
"""

from __future__ import annotations

import json
import urllib.request
from collections.abc import Callable

from olympus.core.sbom import requirements_lines as _requirements_lines

PYPI_JSON_URL = "https://pypi.org/pypi/{name}/{version}/json"

#: A fetcher returns the raw JSON metadata body for one ``name``/``version``.
Fetcher = Callable[[str, str], str]


class LockfileError(RuntimeError):
    """Raised when release metadata cannot be fetched or parsed."""


def _pinned_versions(
    root: str = "olympus-security", extras: frozenset[str] = frozenset()
) -> dict[str, str]:
    """Return ``{name: version}`` for the installed runtime closure."""
    pins: dict[str, str] = {}
    for line in _requirements_lines(root, extras):
        name, version = line.split("==", 1)
        pins[name] = version
    return pins


def _http_fetch(name: str, version: str, timeout: float = 30.0) -> str:
    url = PYPI_JSON_URL.format(name=name, version=version)
    request = urllib.request.Request(url, headers={"Accept": "application/json"})  # noqa: S310
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
            body: str = response.read().decode("utf-8")
            return body
    except (OSError, ValueError) as exc:
        raise LockfileError(f"cannot fetch PyPI metadata for {name}=={version}: {exc}") from exc


def release_hashes_from_metadata(name: str, version: str, body: str) -> list[str]:
    """Return the sorted SHA-256 digests of every file for one release.

    ``pip --require-hashes`` accepts a match against *any* listed hash, so all
    of a version's distribution files (each wheel plus the sdist) are included.
    """
    try:
        metadata = json.loads(body)
    except json.JSONDecodeError as exc:
        raise LockfileError(f"invalid PyPI metadata for {name}=={version}: {exc}") from exc
    files = metadata.get("urls")
    if not isinstance(files, list) or not files:
        raise LockfileError(f"PyPI lists no files for {name}=={version}")
    digests: set[str] = set()
    for entry in files:
        if entry.get("yanked"):
            continue  # never pin to a yanked artifact
        digest = (entry.get("digests") or {}).get("sha256")
        if isinstance(digest, str) and digest:
            digests.add(digest)
    if not digests:
        raise LockfileError(f"no SHA-256 digest published for {name}=={version}")
    return sorted(digests)


def fetch_release_hashes(
    pins: dict[str, str], fetcher: Fetcher | None = None
) -> dict[str, list[str]]:
    """Return ``{name: [sha256, ...]}`` for every pinned package.

    ``fetcher`` defaults to the live PyPI fetch, resolved at call time so tests
    can monkeypatch :func:`_http_fetch`.
    """
    resolve = fetcher or _http_fetch
    return {
        name: release_hashes_from_metadata(name, version, resolve(name, version))
        for name, version in sorted(pins.items())
    }


def render_constraints(
    pins: dict[str, str], hashes: dict[str, list[str]], *, header: bool = True
) -> str:
    """Render a ``pip --require-hashes`` constraints document.

    Each requirement is emitted as ``name==version`` followed by one
    ``--hash=sha256:<digest>`` continuation per published file, in the multi-line
    form pip expects.
    """
    lines: list[str] = []
    if header:
        lines += [
            "# Hash-pinned constraints for the Olympus runtime closure.",
            "# Generated by `olympus core lock` from the PyPI JSON API — do not edit by hand.",
            "# Install with: pip install --require-hashes -r constraints.txt",
            "",
        ]
    for name in sorted(pins):
        digests = hashes.get(name)
        if not digests:
            raise LockfileError(f"no hashes resolved for {name}")
        first, *rest = digests
        # pip's grammar: the first hash may sit on the requirement line; every
        # further hash is its own backslash-continued line.
        if rest:
            lines.append(f"{name}=={pins[name]} \\")
            for digest in [first, *rest]:
                trailing = " \\" if digest != digests[-1] else ""
                lines.append(f"    --hash=sha256:{digest}{trailing}")
        else:
            lines.append(f"{name}=={pins[name]} --hash=sha256:{first}")
    return "\n".join(lines) + "\n"


def generate_lockfile(
    root: str = "olympus-security",
    extras: frozenset[str] = frozenset(),
    fetcher: Fetcher | None = None,
) -> str:
    """Fetch hashes for the runtime closure and render the constraints file."""
    pins = _pinned_versions(root, extras)
    hashes = fetch_release_hashes(pins, fetcher)
    return render_constraints(pins, hashes)
